steps:
- name: node
  entrypoint: npm
  args: ['install','--prefix','frontEnd']
- name: node
  entrypoint: npm
  args: ['install', '-g', '@vue/cli']
- name: node
  entrypoint: npm
  args: ['test','--prefix','frontEnd']
- name: node
  entrypoint: npm
  args: ['run', 'build','--prefix','frontEnd']
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy",'~/frontEnd/app.yaml']