# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "selatt-db"
      MYSQL_USER: "selatt-db"
      MYSQL_PASSWORD: "s3l4tt-db"
      MYSQL_ROOT_PASSWORD: "example"
  
    ports:
      - 3306:3306
    expose:
      - 3306


  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

